### ISSUE TITLE
add missing  three.js\examples\js\loaders types?

### ISSUE THREAD

**Issue by sonygod** [tong/three.hx#6]
add miss three.js\examples\js\loaders types?

src path

three.js\examples\js\loaders

![image](https://user-images.githubusercontent.com/748320/56092372-ff009880-5eed-11e9-8e79-2dca19f95d09.png)

**Comment by tong** [comment]
Don't want to add externs from examples/ here, just from core library.  
Here https://github.com/omlib/om.three/tree/master/src/om/three/loader are some loader externs i've been using.
