### ISSUE TITLE
threejs_include doesn't seem to work

### ISSUE THREAD

**Issue by MatthijsKamstra** [tong/three.hx#9]
simple example:

```
class MainTest {
	static function main() {
		trace("Hello, world!");
	}
}
```

build.hxml

```
-lib three.hx
-cp src
-main MainTest
-js bin/include_debug.js
-dce full
-debug
-D threejs_include

--next

-lib three.hx
-cp src
-main MainTest
-js bin/include.js
-dce full
# -debug
-D threejs_include
```

does not embed `three.js`

**Comment by tong** [comment]
Works for me, not sure why it should not.

**Comment by MatthijsKamstra** [comment]
![Screenshot 2019-11-18 at 13 45 28](https://user-images.githubusercontent.com/907219/69053451-b839ca80-0a09-11ea-9258-b5dbff4babe8.png)

I am probably missing something very obvious, but I can't get it to work.

**Comment by tong** [comment]
Can't reproduce.
I've copy/paste your example and it works as expected.

**Comment by MatthijsKamstra** [comment]
This is mysterious... 🤪
Well it is what it is... If it works, it works.

You can close the issue.
